2016-01-20 16:22:32,641-logger.basedata-ERROR-not enough arguments for format string
2016-01-20 16:22:32,644-logger.basedata-ERROR-?
2016-01-20 16:25:09,740-logger.basedata-ERROR-not enough arguments for format string
2016-01-20 16:26:28,069-logger.basedata-ERROR-not enough arguments for format string
2016-01-20 16:29:00,038-logger.basedata-ERROR-near "'dir'": syntax error
2016-01-20 16:30:55,266-logger.basedata-ERROR-near "'direct'": syntax error
2016-01-20 16:32:53,214-logger.basedata-ERROR-near "'direct'": syntax error
2016-01-21 10:51:12,243-logger.basedata-WARNING-the directory name 'one' already exist.
2016-01-21 10:51:12,243-logger.basedata-WARNING-the directory name 'one' already exist.
2016-01-21 10:51:50,852-logger.basedata-WARNING-the directory name 'one' already exist.
2016-01-21 10:52:41,420-logger.basedata-WARNING-the directory name 'one' already exist.
2016-01-21 10:53:10,334-logger.basedata-WARNING-the directory name 'two' already exist.
2016-01-21 10:53:47,671-logger.basedata-WARNING-the directory name 'two' already exist.
2016-01-21 10:54:09,841-logger.basedata-WARNING-the directory name 'two' already exist.
2016-01-21 10:54:34,641-logger.basedata-WARNING-the directory name 'tw' already exist.
2016-01-21 10:54:46,375-logger.basedata-WARNING-the directory name 'tw' already exist.
2016-01-21 10:55:02,911-logger.basedata-WARNING-the directory name 'tw' already exist.
2016-01-21 10:55:20,657-logger.basedata-WARNING-the directory name 'tw' already exist.
2016-01-21 10:58:05,092-logger.basedata-WARNING-the directory name 'a' already exist.
2016-01-21 10:58:17,953-logger.basedata-WARNING-the directory name 'a' already exist.
2016-01-21 11:02:37,806-logger.basedata-INFO-no such directory
2016-01-21 11:03:00,167-logger.basedata-INFO-no such directory
2016-01-21 11:05:27,904-logger.basedata-INFO-no such directory
2016-01-21 11:06:31,769-logger.basedata-INFO-no such directory
2016-01-21 11:56:11,778-logger.basedata-INFO-the user name 'tmp' already exist in k
2016-01-21 11:56:20,878-logger.basedata-INFO-the user name 'tmp' already exist in k
2016-01-21 11:56:56,267-logger.basedata-INFO-the user name 'tmp' already exist in k
2016-01-21 13:45:04,398-logger.basedata-INFO-the user name 'a' don't exist in tmp
2016-01-21 13:51:51,158-logger.basedata-ERROR-cannot concatenate 'str' and 'list' objects
2016-01-21 13:53:03,411-logger.basedata-INFO-the user name '1' don't exist in tmp
2016-01-21 14:00:01,585-logger.basedata-INFO-the user name 'a' already exist in tmp
2016-01-21 14:00:11,257-logger.basedata-INFO-the user name 'a' already exist in tmp
2016-01-21 14:01:49,480-logger.basedata-INFO-the user name 'a' don't exist in tmp
2016-01-21 14:02:44,460-logger.basedata-INFO-the user name 'a' don't exist in tmp's write list
2016-01-21 14:42:58,859-logger.basedata-INFO-the user name 'a' don't exist in tmp's write list
2016-01-21 14:46:53,450-logger.basedata-INFO-the user name 'aaaa' already exist in tmp's valid users
2016-01-21 14:47:17,581-logger.basedata-INFO-the user name 'aaaa' already exist in tmp's valid users
2016-01-21 14:47:17,582-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 14:47:31,486-logger.basedata-INFO-the user name 'aaaa' already exist in tmp's valid users
2016-01-21 14:47:31,486-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 14:47:35,566-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 14:48:19,076-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 14:48:47,428-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 14:48:47,595-logger.dirbase-ERROR-the type of directory name is wrong
2016-01-21 14:49:50,651-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 14:49:50,828-logger.dirbase-ERROR-the type of directory name is wrong
2016-01-21 16:20:29,295-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 16:20:54,469-logger.dirbase-ERROR-the directory name 'tmp' don't exist
2016-01-21 16:20:54,497-logger.basedata-INFO-no such directory
2016-01-21 16:22:11,903-logger.dirbase-ERROR-the directory name 'tmp' don't exist
2016-01-21 16:22:11,913-logger.basedata-INFO-no such directory
2016-01-21 16:22:57,558-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 16:24:23,372-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 16:28:28,983-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 16:28:29,207-logger.dirbase-ERROR-the type of directory name is wrong
2016-01-21 16:32:31,476-logger.basedata-INFO-the user name '545' don't exist in tmp's valid users
2016-01-21 16:32:31,711-logger.dirbase-ERROR-the type of directory name is wrong
2016-01-21 16:48:42,947-logger.basedirection-ERROR-test
2016-01-21 16:57:57,733-logger.basedirection-ERROR-test
2016-01-21 17:02:00,819-logger.basedata-INFO-update direct set valid_users = 'a' where name = 'tmp'
2016-01-21 17:10:26,862-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-21 17:10:31,990-logger.basedata-INFO-update direct set write_list = '' where name = 'tmp'
2016-01-21 17:10:32,072-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-21 17:11:28,371-logger.basedata-INFO-update direct set write_list = '' where name = 'tmp'
2016-01-21 17:11:28,447-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-21 17:11:28,529-logger.basedata-INFO-INSERT INTO direct SELECT 'one', '/nas/',valid_users,force_user,force_group,read_only,create_mask,directory_mask,guest_ok,write_list FROM direct WHERE name='tmp'
2016-01-21 17:11:38,921-logger.basedata-INFO-update direct set write_list = '' where name = 'tmp'
2016-01-21 17:11:38,987-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-21 17:11:38,989-logger.basedata-WARNING-the directory name 'one' already exist.
2016-01-21 17:12:13,680-logger.basedata-INFO-update direct set write_list = '' where name = 'tmp'
2016-01-21 17:12:13,755-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-21 17:15:39,792-logger.basedata-INFO-update direct set write_list = '' where name = 'tmp'
2016-01-21 17:15:39,927-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-22 14:00:45,252-logger.fabfile-INFO-test
2016-01-22 18:07:58,007-logger.basedata-INFO-update direct set valid_users = 'a,aaaa' where name = 'tmp'
2016-01-22 18:07:58,141-logger.basedata-INFO-update direct set valid_users = 'a' where name = 'tmp'
2016-01-22 18:07:58,240-logger.basedata-INFO-update direct set write_list = 'a,aaa' where name = 'tmp'
2016-01-22 18:07:58,335-logger.basedata-INFO-update direct set write_list = 'a' where name = 'tmp'
2016-01-28 14:05:44,806-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:07:54,227-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:08:38,313-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:08:38,408-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:08:38,410-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:10:39,411-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:10:39,601-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:10:39,601-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:10:39,601-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:47:11,286-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:47:11,381-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:47:11,381-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:48:27,108-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:48:27,164-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 14:48:27,164-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 16:34:27,648-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 16:34:27,733-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 16:34:27,733-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 16:35:14,971-logger.group-ERROR-some error arise when get attribute of root:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 16:35:15,032-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
2016-01-28 16:35:15,032-logger.group-ERROR-some error arise when get attribute of ftp:[Errno 2] No such file or directory: u'/etc/group'
